### ISSUE TITLE
Cavab

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [gurbangurbanzade/PragmatechFrontEndProject#10]
"Araşdırma suallarını geniş şəkildə cavablandıraraq research.md faylına yerləşdirin.Növbəti dərsin mövzuları haqqında da olan suallara öz araşdırmanıza görə cavablar yazsanız çox əla olar." burada müəllim istəyirsiniz yazın, istəmirsiniz yazmayın deyə bir şey deməyib. Bundan əlavə də nəsə deməyib. Sizə deyə bilər, amma mənim gördüyüm bu iki cümlə olduğu üçün onları da nəzərə almışam normal olaraq. Yazanlar var. Zöhrabın yazdığına baxa bilərsiniz. 1-ci cümlədə müəllim geniş şəkildə yazın deyib. Sizin dediyiniz quizlərə aid idi, bu başqa bir şeydir. Yazılmayanlar isə 1.4 və 3-cü hissə. Xoşdur. :)

**Comment by gurbangurbanzade** [comment]
Zöhrabın adına sevindim). Bu günə qədər olan taskların bütün araşdırmalarına "Suallara cavab yazmağınız yaxşıdır.👍🏼" rəyini vermisiniz. Artıq düzgünlüyü və səhvliyini yoxlamağınız məni sevindirdi. 1.4 sualda özüm üçün yazıb yoldaşımla yoxlamışam. 3-cü hissəyə görə müzakirə etməyəcəm çünki bura sosial şəbəkə deyil və yazdıqca görürəm ki, uzanır. Əgər yenə fikir bildirmək istəsəniz mail üzərindən yazın zəhmət olmasa müzakirə edək :)

**Comment by isbendiyarovanezrin** [comment]
Çünki onda müəllim demişdi ki, suallara baxma, əsas verilən tapşırığı yoxla və mən əlavə olaraq sualları yazana artıq bal verirdim. Bu gün isə bildiyiniz və gördüyünüz kimi əsas tapşırıq suallardır.

Zöhrabın adına sevinin deyə demədim ki onu. Ona görə dedim ki, baxın görək necə yazmaq lazımdır.

1.4-cü sualı yazmısınız yazın ki, yazmışam. Yoxsa mən necə bilə bilərəm?

E-poçt üzərindən niyə yazıram ki, telefon ola-ola?😅 Başa düşmədim sizin bəzi cümlələrinizi. 3-cü hissəni yazmayıb üstəlik balınızın kəsilməməsini istəyirsiniz?🤷🏻‍♀️

**Comment by isbendiyarovanezrin** [comment]
1.4-cü sualı yazmısınız yazın ki, yazmışam. Sizin evdə nə etdiyinizi mən necə bilim?

**Comment by isbendiyarovanezrin** [comment]
E-poçt üzərindən niyə yazıram ki, telefon ola-ola?😅 Başa düşmədim sizin bəzi cümlələrinizi. 3-cü hissəni yazmayıb üstəlik balınızın kəsilməməsini istəyirsiniz?
